#ifdef PEAR_PLATFORM_GLFW

#ifndef PEAR_EVENT_GLFW_MOUSE_H_
#define PEAR_EVENT_GLFW_MOUSE_H_

// from glfw3.h

#define PEAR_PLATFORM_MOUSE_BUTTON_1         0
#define PEAR_PLATFORM_MOUSE_BUTTON_2         1
#define PEAR_PLATFORM_MOUSE_BUTTON_3         2
#define PEAR_PLATFORM_MOUSE_BUTTON_4         3
#define PEAR_PLATFORM_MOUSE_BUTTON_5         4
#define PEAR_PLATFORM_MOUSE_BUTTON_6         5
#define PEAR_PLATFORM_MOUSE_BUTTON_7         6
#define PEAR_PLATFORM_MOUSE_BUTTON_8         7
#define PEAR_PLATFORM_MOUSE_BUTTON_LAST      PEAR_PLATFORM_MOUSE_BUTTON_8
#define PEAR_PLATFORM_MOUSE_BUTTON_LEFT      PEAR_PLATFORM_MOUSE_BUTTON_1
#define PEAR_PLATFORM_MOUSE_BUTTON_RIGHT     PEAR_PLATFORM_MOUSE_BUTTON_2
#define PEAR_PLATFORM_MOUSE_BUTTON_MIDDLE    PEAR_PLATFORM_MOUSE_BUTTON_3
#define PEAR_PLATFORM_MOUSE_BUTTON_UNKNOWN   0xFFFF

#endif

#endif
