#ifndef PEAR_LINUX_KEYBOARD_H
#define PEAR_LINUX_KEYBOARD_H

#define PEAR_KEY_UNKNOWN1
#define PEAR_KEY_SPACE
#define PEAR_KEY_APOSTROPHE
#define PEAR_KEY_COMMA
#define PEAR_KEY_MINUS
#define PEAR_KEY_PERIOD
#define PEAR_KEY_SLASH
#define PEAR_KEY_0
#define PEAR_KEY_1
#define PEAR_KEY_2
#define PEAR_KEY_3
#define PEAR_KEY_4
#define PEAR_KEY_5
#define PEAR_KEY_6
#define PEAR_KEY_7
#define PEAR_KEY_8
#define PEAR_KEY_9
#define PEAR_KEY_SEMICOLON
#define PEAR_KEY_EQUAL
#define PEAR_KEY_A
#define PEAR_KEY_B
#define PEAR_KEY_C
#define PEAR_KEY_D
#define PEAR_KEY_E
#define PEAR_KEY_F
#define PEAR_KEY_G
#define PEAR_KEY_H
#define PEAR_KEY_I
#define PEAR_KEY_J
#define PEAR_KEY_K
#define PEAR_KEY_L
#define PEAR_KEY_M
#define PEAR_KEY_N
#define PEAR_KEY_O
#define PEAR_KEY_P
#define PEAR_KEY_Q
#define PEAR_KEY_R
#define PEAR_KEY_S
#define PEAR_KEY_T
#define PEAR_KEY_U
#define PEAR_KEY_V
#define PEAR_KEY_W
#define PEAR_KEY_X
#define PEAR_KEY_Y
#define PEAR_KEY_Z
#define PEAR_KEY_LEFT_BRACKET
#define PEAR_KEY_BACKSLASH
#define PEAR_KEY_RIGHT_BRACKET
#define PEAR_KEY_GRAVE_ACCENT
#define PEAR_KEY_WORLD_1
#define PEAR_KEY_WORLD_2
#define PEAR_KEY_ESCAPE
#define PEAR_KEY_ENTER
#define PEAR_KEY_TAB
#define PEAR_KEY_BACKSPACE
#define PEAR_KEY_INSERT
#define PEAR_KEY_DELETE
#define PEAR_KEY_RIGHT
#define PEAR_KEY_LEFT
#define PEAR_KEY_DOWN
#define PEAR_KEY_UP
#define PEAR_KEY_PAGE_UP
#define PEAR_KEY_PAGE_DOWN
#define PEAR_KEY_HOME
#define PEAR_KEY_END
#define PEAR_KEY_CAPS_LOCK
#define PEAR_KEY_SCROLL_LOCK
#define PEAR_KEY_NUM_LOCK
#define PEAR_KEY_PRINT_SCREEN
#define PEAR_KEY_PAUSE
#define PEAR_KEY_F1
#define PEAR_KEY_F2
#define PEAR_KEY_F3
#define PEAR_KEY_F4
#define PEAR_KEY_F5
#define PEAR_KEY_F6
#define PEAR_KEY_F7
#define PEAR_KEY_F8
#define PEAR_KEY_F9
#define PEAR_KEY_F10
#define PEAR_KEY_F11
#define PEAR_KEY_F12
#define PEAR_KEY_F13
#define PEAR_KEY_F14
#define PEAR_KEY_F15
#define PEAR_KEY_F16
#define PEAR_KEY_F17
#define PEAR_KEY_F18
#define PEAR_KEY_F19
#define PEAR_KEY_F20
#define PEAR_KEY_F21
#define PEAR_KEY_F22
#define PEAR_KEY_F23
#define PEAR_KEY_F24
#define PEAR_KEY_F25
#define PEAR_KEY_KP_0
#define PEAR_KEY_KP_1
#define PEAR_KEY_KP_2
#define PEAR_KEY_KP_3
#define PEAR_KEY_KP_4
#define PEAR_KEY_KP_5
#define PEAR_KEY_KP_6
#define PEAR_KEY_KP_7
#define PEAR_KEY_KP_8
#define PEAR_KEY_KP_9
#define PEAR_KEY_KP_DECIMAL
#define PEAR_KEY_KP_DIVIDE
#define PEAR_KEY_KP_MULTIPLY
#define PEAR_KEY_KP_SUBTRACT
#define PEAR_KEY_KP_ADD
#define PEAR_KEY_KP_ENTER
#define PEAR_KEY_KP_EQUAL
#define PEAR_KEY_LEFT_SHIFT
#define PEAR_KEY_LEFT_CONTROL
#define PEAR_KEY_LEFT_ALT
#define PEAR_KEY_LEFT_SUPER
#define PEAR_KEY_RIGHT_SHIFT
#define PEAR_KEY_RIGHT_CONTROL
#define PEAR_KEY_RIGHT_ALT
#define PEAR_KEY_RIGHT_SUPER
#define PEAR_KEY_MENU

#endif
