#ifndef PEAR_MOUSE_H
#define PEAR_MOUSE_H

#ifdef PEAR_PLATFORM_LINUX
    #include <event/platform/linux/mouse.h>
#endif

#define PEAR_MOUSE_BUTTON_1      PEAR_PLATFORM_MOUSE_BUTTON_1
#define PEAR_MOUSE_BUTTON_2      PEAR_PLATFORM_MOUSE_BUTTON_2
#define PEAR_MOUSE_BUTTON_3      PEAR_PLATFORM_MOUSE_BUTTON_3
#define PEAR_MOUSE_BUTTON_4      PEAR_PLATFORM_MOUSE_BUTTON_4
#define PEAR_MOUSE_BUTTON_5      PEAR_PLATFORM_MOUSE_BUTTON_5
#define PEAR_MOUSE_BUTTON_6      PEAR_PLATFORM_MOUSE_BUTTON_6
#define PEAR_MOUSE_BUTTON_7      PEAR_PLATFORM_MOUSE_BUTTON_7
#define PEAR_MOUSE_BUTTON_8      PEAR_PLATFORM_MOUSE_BUTTON_8
#define PEAR_MOUSE_BUTTON_LAST   PEAR_PLATFORM_MOUSE_BUTTON_LAST
#define PEAR_MOUSE_BUTTON_LEFT   PEAR_PLATFORM_MOUSE_BUTTON_LEFT
#define PEAR_MOUSE_BUTTON_RIGHT  PEAR_PLATFORM_MOUSE_BUTTON_RIGHT
#define PEAR_MOUSE_BUTTON_MIDDLE PEAR_PLATFORM_MOUSE_BUTTON_MIDDLE

#endif
