#ifndef PEAR_EVENT_MOUSE_H_
#define PEAR_EVENT_MOUSE_H_

#include <event/platform/glfw/mouse.h>

#define PEAR_MOUSE_BUTTON_LEFT      PEAR_PLATFORM_MOUSE_BUTTON_LEFT
#define PEAR_MOUSE_BUTTON_RIGHT     PEAR_PLATFORM_MOUSE_BUTTON_RIGHT
#define PEAR_MOUSE_BUTTON_MIDDLE    PEAR_PLATFORM_MOUSE_BUTTON_MIDDLE
#define PEAR_MOUSE_BUTTON_UNKNOWN   PEAR_PLATFORM_MOUSE_BUTTON_UNKNOWN

#endif
